# -*- coding: utf-8 -*-
"""Automate_Jujun-Munawar

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14FP0HpJQ30WLJ6oy9OyPCCHERuG6cVVq

# **1. Perkenalan Dataset**

Dataset mencakup profil pasien dengan beragam fitur yang mencerminkan demografi, kebiasaan gaya hidup, riwayat keluarga, serta pengukuran klinis yang diakui sebagai indikator penting risiko Dataset telah melalui proses **pembersihan** dan **pra-pemrosesan**, sehingga siap digunakan untuk berbagai tujuan seperti klasifikasi, regresi, rekayasa fitur, analisis statistik, dan visualisasi data.diabetes. Semua data dihasilkan menggunakan distribusi statistik yang didasarkan pada penelitian medis dunia nyata, sehingga menjamin privasi sekaligus tetap mencerminkan pola kesehatan yang realistis.

Tahap pertama, Anda harus mencari dan menggunakan dataset dengan ketentuan sebagai berikut:

1. **Sumber Dataset**:  
   Dataset dapat diperoleh dari berbagai sumber, seperti public repositories (*Kaggle*, *UCI ML Repository*, *Open Data*) atau data primer yang Anda kumpulkan sendiri.

# **2. Import Library**

Pada tahap ini, Anda perlu mengimpor beberapa pustaka (library) Python yang dibutuhkan untuk analisis data dan pembangunan model machine learning atau deep learning.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import joblib
import time

from google.colab import files
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import classification_report
#model
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier

#evaluasi
from sklearn.metrics import accuracy_score, precision_score,recall_score,auc,roc_curve,confusion_matrix,classification_report,f1_score

"""# **3. Memuat Dataset**

Pada tahap ini, Anda perlu memuat dataset ke dalam notebook. Jika dataset dalam format CSV, Anda bisa menggunakan pustaka pandas untuk membacanya. Pastikan untuk mengecek beberapa baris awal dataset untuk memahami strukturnya dan memastikan data telah dimuat dengan benar.

Jika dataset berada di Google Drive, pastikan Anda menghubungkan Google Drive ke Colab terlebih dahulu. Setelah dataset berhasil dimuat, langkah berikutnya adalah memeriksa kesesuaian data dan siap untuk dianalisis lebih lanjut.

Jika dataset berupa unstructured data, silakan sesuaikan dengan format seperti kelas Machine Learning Pengembangan atau Machine Learning Terapan
"""

path ="/content/diabetes_dataset.csv"
df = pd.read_csv(path)
df.head()

"""# **4. Exploratory Data Analysis (EDA)**

Pada tahap ini, Anda akan melakukan **Exploratory Data Analysis (EDA)** untuk memahami karakteristik dataset.

Tujuan dari EDA adalah untuk memperoleh wawasan awal yang mendalam mengenai data dan menentukan langkah selanjutnya dalam analisis atau pemodelan.
"""

df.info()

df.isnull().sum()

df.duplicated().sum()

df.describe()

plt.figure(figsize=(10, 6))
sns.countplot(x='diagnosed_diabetes',data=df)
plt.title('Diagnosis Diabetes')
plt.xlabel('Diagnosis')
plt.ylabel('Count')
plt.show()

"""# **5. Data Preprocessing**

Pada tahap ini, data preprocessing adalah langkah penting untuk memastikan kualitas data sebelum digunakan dalam model machine learning.

Jika Anda menggunakan data teks, data mentah sering kali mengandung nilai kosong, duplikasi, atau rentang nilai yang tidak konsisten, yang dapat memengaruhi kinerja model. Oleh karena itu, proses ini bertujuan untuk membersihkan dan mempersiapkan data agar analisis berjalan optimal.

Berikut adalah tahapan-tahapan yang bisa dilakukan, tetapi **tidak terbatas** pada:
1. Menghapus atau Menangani Data Kosong (Missing Values)
2. Menghapus Data Duplikat
3. Normalisasi atau Standarisasi Fitur
4. Deteksi dan Penanganan Outlier
5. Encoding Data Kategorikal
6. Binning (Pengelompokan Data)

Cukup sesuaikan dengan karakteristik data yang kamu gunakan yah. Khususnya ketika kami menggunakan data tidak terstruktur.
"""

X = df.drop(columns = ['diagnosed_diabetes', 'diabetes_stage'])
Y = df.diagnosed_diabetes

X_df, X_test, Y_df, Y_test = train_test_split(X,Y, test_size=0.1, random_state=42,stratify=Y)

X_train, X_val, Y_train, Y_val = train_test_split(X,Y, test_size=0.2, random_state=42,stratify=Y)

X_train = X_train[[
    'diabetes_risk_score'
    ,'hba1c'
    ,'glucose_postprandial'
    ,'glucose_fasting'
    ,'family_history_diabetes'
    ,'hypertension_history'
    ,'cardiovascular_history'
]]
X_val = X_val[['diabetes_risk_score',
        'hba1c',
        'glucose_postprandial',
        'glucose_fasting',
       'family_history_diabetes',
       'hypertension_history',
       'cardiovascular_history']]

Y_train = Y_train.values
Y_val = Y_val.values
relevant_categorical = ['family_history_diabetes','hypertension_history','cardiovascular_history']
relevant_numeric = ['diabetes_risk_score', 'hba1c', 'glucose_postprandial', 'glucose_fasting']

#standarisasi
scaler = StandardScaler()

X_train_categorical = X_train[relevant_categorical].values
X_val_categorical = X_val[relevant_categorical].values

X_train_numeric = X_train[relevant_numeric]
X_val_numeric = X_val[relevant_numeric]


scaler.fit(X_train_numeric)
X_train_scaled = scaler.transform(X_train_numeric)
X_val_scaled = scaler.transform(X_val_numeric)

X_train_processed = np.concatenate((X_train_scaled, X_train_categorical), axis = 1)
X_val_processed = np.concatenate((X_val_scaled, X_val_categorical), axis = 1)

models = [LogisticRegression(class_weight='balanced'),
          RandomForestClassifier(class_weight='balanced'),
          KNeighborsClassifier(),
          SVC(class_weight='balanced')
         ]
model_name = [type(model).__name__ for model in models]
accuracy = []
training_times = []
fitted_models = []
for i, model in enumerate(models):
    start = time.process_time()
    fitted_model = model.fit(X_train_processed, Y_train)
    fitted_models.append(fitted_model)
    end = time.process_time()
    y_pred = fitted_model.predict(X_val_processed)
    print('model ', model_name[i],' fitted')
    accuracy.append(accuracy_score(Y_val, y_pred))
    training_times.append(np.round(end-start, 4))

models_result = pd.DataFrame(
    {'models':model_name,
    'accuracy':accuracy,
     'training_time':training_times
    }
)

display(models_result)

model_result_accuracy_sorted = models_result.sort_values(by=['accuracy'], ascending=False)
model_result_time_sorted = models_result.sort_values(by=['training_time'],ascending=False)

X_test_categorical = X_test[relevant_categorical].values
X_test_numeric = X_test[relevant_numeric]

X_test_scaled = scaler.transform(X_test_numeric)

X_test_processed = np.concatenate((X_test_scaled, X_test_categorical), axis = 1)

model = fitted_models[1] ###Random Forest

y_pred = model.predict(X_test_processed)

print('Accuarcy: ', accuracy_score(Y_test, y_pred))
print('Recall: ', recall_score(Y_test, y_pred))
print('Precision: ',precision_score(Y_test, y_pred))
fpr, tpr, thresholds = roc_curve(Y_test, y_pred)
roc_auc = auc(fpr, tpr)
print('Auc: ',roc_auc)